### PR TITLE
Send Origin header with https:// schema for secure requests

### PR DESCRIPTION
**Pull request by rpuch**
Otherwise, Origin validation fails for such requests

Signed-off-by: Roman Puchkovskiy <roman.puchkovskiy@gmail.com>

### CODE REVIEW

**Comment by jansupol** [comment]
I am +1 for the change but need to file a CQ for spring-boot (only a committer can do so)

**Comment by jansupol** [comment]
I am +1 for the change but need to file a CQ for spring-boot (only a committer can do so)

**Comment by rpuch** [comment]
Hi @jansupol. Thanks for your reply. Do I need to do anything to help get the CQ filed, or should I just patiently wait?

Also, I have a stupid question. What is CQ? :)

**Comment by jansupol** [comment]
I have created a [Wiki describing CQs](https://github.com/eclipse-ee4j/tyrus/wiki/About-CQs).

Unfortunately, there is nothing you can do regarding CQs at the moment.

**Comment by rpuch** [comment]
Thank you for the page, I learned something new today

**Comment by arjantijms** [comment]
> I have created a [Wiki describing CQs](https://github.com/eclipse-ee4j/tyrus/wiki/About-CQs).

I still find the process very, very painful. Perhaps we should bundle some resources to create a plug-in that checks for this automatically, and, with an option, also files the CQs if needed in a semi-automated way.

**Comment by jansupol** [comment]
> I still find the process very, very painful.

I agree. There is another issue with the CQ. The CQ might not get approved before the Release Review and the IP log would not be approved before the release review process, in that case. There is currently a discussion about the IP policy in the Foundation, perhaps there will be some changes. Let's see what the news is.

Let's merge this, exclude the test for the release, and put it back once the release review is done.

**Review by jansupol — APPROVED** [review]

**Pull request merged**
