### PR TITLE
804 revert SslEngineConfigurator support removal in GrizzlyClientSocket

### LINKED ISSUE #804: Revert the removal of the support of org.glassfish.tyrus.client.SslEngineConfigurator in GrizzlyClientSocket
This block of code has been removed by mistake and should be reintroduce : 
(containers/grizzly-client/src/main/java/org/glassfish/tyrus/container/grizzly/client/GrizzlyClientSocket.java#758-761)
```java
if (configuratorObject instanceof SslEngineConfigurator) {
    return new ExtendedSSLEngineConfigurator((SslEngineConfigurator) configuratorObject, uri.getHost());
}
```

see https://github.com/eclipse-ee4j/tyrus/issues/767#issuecomment-1246586394_ for more details

### PR DESCRIPTION
**Pull request by NilsRenaud**
Fixes #804 

Signed-off-by: Nils Renaud <renaud.nils@gmail.com>

### CODE REVIEW

**Review by jansupol — APPROVED** [review]

**Comment by NilsRenaud** [comment]
Thanks for merging this PR @jansupol. Any idea of a release date for the next 2.1.x ?

**Comment by jansupol** [comment]
There is some bug related discussion, so right after that we could make 2.1.1.

**Comment by NilsRenaud** [comment]
It looks like this commit has not been included in the 2.1.1 release. Any reasons why ? 😢

**Comment by jansupol** [comment]
#811

**Comment by jansupol** [comment]
I have marked you as an author,

**Pull request merged**
