### PR TITLE
Locale and Build fixes 

### LINKED ISSUE #622: Failure in org.glassfish.tyrus.core.UtilsTest : "Cannot parse valid date" .
Dear Tyrus Team,

I have tried today 'Clean&Build' with Maven in NetBeans 8.1 on Java 8_151 and getting following issue.

Is there a wrong configuration on my side and 

can you help me please thereby ?

Many thanks and 
Best Regards,
Friedhold

 @Test
    public void testParseHttpDateAnsiCAsc() {
        try {
            Date date = Utils.parseHttpDate("Sun Nov  6 08:49:37 1994");
            assertNotNull("Date cannot be null", date);
        } catch (ParseException e) {
            **_fail("Cannot parse valid date");_**
        }
    }

Test set: org.glassfish.tyrus.core.UtilsTest
-------------------------------------------------------------------------------
Tests run: 4, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 0.014 sec <<< FAILURE! - in org.glassfish.tyrus.core.UtilsTest
testParseHttpDateRfc1123(org.glassfish.tyrus.core.UtilsTest)  Time elapsed: 0.013 sec  <<< FAILURE!
java.lang.AssertionError: Cannot parse valid date
	at org.junit.Assert.fail(Assert.java:93)
	at org.glassfish.tyrus.core.UtilsTest.testParseHttpDateRfc1123(UtilsTest.java:63)

testParseHttpDateAnsiCAsc(org.glassfish.tyrus.core.UtilsTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: Cannot parse valid date
	at org.junit.Assert.fail(Assert.java:93)
	at org.glassfish.tyrus.core.UtilsTest.testParseHttpDateAnsiCAsc(UtilsTest.java:83)

testParseHttpDateRfc1036(org.glassfish.tyrus.core.UtilsTest)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError: Cannot parse valid date
	at org.junit.Assert.fail(Assert.java:93)
	at org.glassfish.tyrus.core.UtilsTest.testParseHttpDateRfc1036(UtilsTest.java:73)

### PR DESCRIPTION
**Pull request by nuessgens**
This pull-request resolves #622 

parse HTTP date is now working on JVMs with non-EN default locales.

Furthermore the build succeeds on non Unix-Systems (e.g. Windows) (fixed Unit-Test by introducing an assumption)

### CODE REVIEW

**Comment by nuessgens** [comment]
I'm pretty sure the failed CI build has nothing to do with any of my changes

> Failed to read artifact descriptor for org.apache.maven.reporting:maven-reporting-impl:jar:2.3: Could not transfer artifact org.apache.maven.reporting:maven-reporting-impl:pom:2.3 from/to google-maven-central (https://maven-central.storage-download.googleapis.com/repos/central/data/): Checksum validation failed, no checksums available

Can one just rebuild it?

**Comment by nuessgens** [comment]
In addition to the original bugfix this pull request _fixes_ the Travis CI build.

Therefore I made to changes
1. Specify `dist: trusty` (otherwise oraclejdk8 would not be available anymore, see https://travis-ci.community/t/install-of-oracle-jdk-8-failing/3038/9 for further info)
1. Changed from strict (`-C`) to lax  (`-c`) checksum validation. Unfortunately the checksum issue still persists with the travis maven mirror (see https://travis-ci.community/t/checksum-validation-fail-using-maven/4005/).  As _other repos_ of the Eclipse EE4J project do not use checksum validation either, I thought this would be okay.

**Comment by jansupol** [comment]
Looks good. Locale.ROOT would maybe be better than Locale.ENGLISH, but both should be safe.

**Comment by bshannon** [comment]
> Locale.ROOT would maybe be better than Locale.ENGLISH, but both should be safe.

I can't tell from the javadocs what exactly Locale.ROOT would do here.
Is there a better spec for Locale.ROOT?  Why do you think it's better here?

**Comment by jansupol** [comment]
I have usually seen `Locale.ROOT` used for these types of use-cases. Form the javadoc the locale is used: 
> as the language/country neutral locale for the locale sensitive operations

While `Locale.ENGLISH` is working fine, my concern is that a user would see it and say: "Ok, I just need to use any distinct Locale, how about my favorite Turkish? In my next PR I surely would use that".  `Locale.ROOT` seems neutral enough to me not to do that mistake.

**Comment by bshannon** [comment]
> I have usually seen `Locale.ROOT` used for these types of use-cases. From the javadoc the locale is used:
> 
> > as the language/country neutral locale for the locale sensitive operations
> 
> While `Locale.ENGLISH` is working fine, my concern is that a user would see it and say: "Ok, I just need to use any distinct Locale, how about my favorite Turkish? In my next PR I surely would use that". `Locale.ROOT` seems neutral enough to me not to do that mistake.

Except I have no idea what Locale.ROOT does!  At least with Locale.English, I know what it does.  Who knows what month names are used by Locale.ROOT?

**Comment by jansupol** [comment]
@bshannon This seems to be a matter of personal preference. It perhaps takes a while to realize what Locale.ROOT does and the native speakers may be happier with Locale.ENGLISH, but it also is possible to google reversed questions about Locale.ENGLISH. Both are fine.

**Pull request merged**
