### PR TITLE
Support ClientEndpointConfig#getSSLContext

### PR DESCRIPTION
**Pull request by jansupol**
Signed-off-by: jansupol <jan.supol@oracle.com>

### CODE REVIEW

**Review by m0mus — APPROVED** [review]
LGTM

**Comment by NilsRenaud** [comment]
I'm facing an issue with this change, is there any reason you removed these lines ?

(containers/grizzly-client/src/main/java/org/glassfish/tyrus/container/grizzly/client/GrizzlyClientSocket.java#758-761)
```java
if (configuratorObject instanceof SslEngineConfigurator) {
    return new ExtendedSSLEngineConfigurator((SslEngineConfigurator) configuratorObject, uri.getHost());
}
```

**Comment by jansupol** [comment]
@NilsRenaud 
As you can see the lines were [duplicated](https://github.com/eclipse-ee4j/tyrus/blob/master/containers/grizzly-client/src/main/java/org/glassfish/tyrus/container/grizzly/client/GrizzlyClientSocket.java#L754) and now Tyrus 2.1.0 contains just a [single copy of that condition](https://github.com/eclipse-ee4j/tyrus/blob/2.x/containers/grizzly-client/src/main/java/org/glassfish/tyrus/container/grizzly/client/GrizzlyClientSocket.java#L764).

The change is only in EE10 branch. If you are using the EE10 branch, could your issue be caused by missing EE10 dependencies? Tyrus 1.19 (EE8), 2.0.4 (EE9) still contain the condition duplicated.

**Comment by NilsRenaud** [comment]
Nop that's not duplicated line, the first line is `org.glassfish.tyrus.client.SslEngineConfigurator` and the second one is `org.glassfish.grizzly.ssl.SSLEngineConfigurator`

The second one allowed us to disable TLS hostname verification.

**Comment by jansupol** [comment]
oops, you are right. That needs to be fixed.

**Comment by jansupol** [comment]
@jansupol 2.1.2 containing the fix is public now.

**Comment by NilsRenaud** [comment]
Thanks a lot @jansupol !

**Pull request merged**
